### PR TITLE
Added dynamic username to hello index

### PR DESCRIPTION
**Pull request by bensussman**
/testing On localhost, confirmed that the username appeared. Tested as two different users.

@H-KE (A.K.A. Darryl THE CODING MACHINE)

### CODE REVIEW

**Comment by bensussman** [comment]
adding @betterzega

**Comment by betterzega** [comment]
This looks great. Would be awesome if we can get some feature tests around it.

**Comment by joejansen** [comment]
domain lgtm, fantastic idea

**Comment by hankedori** [comment]
Conflicts??

**Pull request merged**
